"""The whole GPU run: environments, then every measurement stage, restartable and with a deadline.

    python3 orchestrate.py night       everything (night.sh)
    python3 orchestrate.py check       the same on 2 questions / 40 examples: a quick smoke test (check.sh)
    python3 orchestrate.py setup       only environments and models
    python3 orchestrate.py inference   only 3a, 3b and the regeneration probe (run.sh)
    python3 orchestrate.py train       only the training speed (../nemo_speed/run.sh)
    python3 orchestrate.py author      only the authors' code on this GPU: profile, then 3a (author.sh; e.g. an A100)

Order of the night (most important first):
    1. 3a  the authors' evaluation scripts, unchanged: EAGLE-3 and plain generation, T=0 and T=1
    2. 4   training step speed: the authors' trainer vs NeMo, same data
    3. 5   regeneration probe (how fast the target rewrites the training answers) and the GPU-hour budget
    4. 3b  SGLang: plain server and EAGLE-3 trees, T=0 (and T=1 with three seeds for the paper tree)
    5. 4   NeMo speed-ups: packing, flash-attn 2, torch.compile, FP8, micro-batch 4

Rules:
    - Each result gets a "done" marker (common.finish); a restart skips finished results.
    - A failed stage is recorded as FAILED and the night continues; only NIGHT_SECONDS (default 7 h) or a
      signal stops it. stages.json lists the status of every stage, logs/<mode>/<stage>.log its output.
    - check mode writes to results/smoke, logs/smoke, ../nemo_speed/artifacts/smoke; the night to .../main.
"""
from __future__ import annotations

import argparse
import contextlib
import json
import os
from pathlib import Path
import shutil
import socket
import subprocess
import sys
import time
import urllib.request

from common import (BENCHES, EAGLE_COMMIT, MODELS, NEMO_COMMIT, SCHEMA, atomic_json, atomic_text, digest,
                    done_path, file_hash, finish, finished, questions, read_json, run_process, terminate_owned,
                    validate_answers, validate_speed)

HERE = Path(__file__).resolve().parent                 # .../inference_speed
TRAIN_DIR = HERE.parent / 'nemo_speed'                 # .../nemo_speed (training data and scripts)

# Training data: Llama-3.1-8B-Instruct answers regenerated by the target (dataset revision is pinned).
TRAIN_DATA_REVISION = 'c8cf5337f3a4bed5ba9da7362446cc5111fd24f1'

# Draft trees. The EAGLE-3 paper (appendix) uses depth 8 (EAGLE-2: 6) with 60 tokens and top-k 10.
# The authors' code counts depth as draft length - 1, so depth 8 is --depth 7 (EaModel's default; the eval
# scripts' own default --depth 5 is the EAGLE-2 tree). SGLang's num-steps is the draft length itself.
AUTHOR_TREE = {'total_token': 60, 'depth': 7, 'top_k': 10}
SGLANG_TREES = [            # name, num-steps, eagle-topk, num-draft-tokens
    ('paper_8_10_60', 8, 10, 60),     # the paper's tree
    ('chain_3_1_4', 3, 1, 4),         # NeMo's serve_sglang default: one chain of 3
    ('docs_5_8_32', 5, 8, 32),        # SGLang documentation's setting for this draft
    ('eagle2_6_10_60', 6, 10, 60),    # EAGLE-2 tree, comparable to the authors' --depth 5 run
]
SGLANG_T1_CONFIGS = ('base', 'paper_8_10_60')    # also measured at T=1, three seeds


def http_json(url, timeout=5):
    with urllib.request.urlopen(url, timeout=timeout) as response:
        return json.load(response)


class Night:
    def __init__(self, mode):
        self.mode = mode
        self.smoke = mode == 'check' or os.environ.get('SMOKE', '0') == '1'
        self.tag = 'smoke' if self.smoke else 'main'
        self.results = HERE / 'results' / self.tag
        self.logs = HERE / 'logs' / self.tag
        self.train_out = TRAIN_DIR / 'artifacts' / self.tag
        for folder in (self.results, self.logs, self.train_out):
            folder.mkdir(parents=True, exist_ok=True)

        self.stages_path = self.results / 'stages.json'
        try:
            self.stages = read_json(self.stages_path)
        except (OSError, ValueError):
            self.stages = {}
        seconds = int(os.environ.get('NIGHT_SECONDS', '25200'))
        if seconds <= 0:
            raise ValueError('NIGHT_SECONDS must be positive')
        self.deadline = time.monotonic() + seconds

        self.model = HERE / 'models/llama31-8b-instruct'
        self.draft = HERE / 'models/eagle3-llama31-8b'
        self.questions_per_bench = 2 if self.smoke else 80
        self.train_examples = 40 if self.smoke else int(os.environ.get('N', '1000'))
        self.warmup_steps = 0 if self.smoke else int(os.environ.get('WARMUP', '20'))
        if self.train_examples <= 2 * self.warmup_steps or self.train_examples % 2:
            raise ValueError('N must be even and leave measured optimizer steps')

        # Interpreters of the four environments.
        self.py_eagle = HERE / 'venv_eagle/bin/python'                 # authors' eval scripts
        self.py_sglang = HERE / 'venv_sglang/bin/python'               # SGLang server and clients
        self.py_original = TRAIN_DIR / 'venv_orig/bin/python'          # authors' trainer + DeepSpeed
        self.py_nemo = TRAIN_DIR / 'Automodel/.venv/bin/python'       # NeMo AutoModel

        self.env = dict(os.environ)
        self.env.update({
            'PYTHONUNBUFFERED': '1', 'WANDB_MODE': 'disabled', 'WANDB_DISABLED': 'true',
            'SGLANG_ENABLE_JIT_DEEPGEMM': '0', 'SGL_ENABLE_JIT_DEEPGEMM': '0',   # DeepGEMM needs a CUDA toolkit
            'TRAIN_DATA_REVISION': TRAIN_DATA_REVISION, 'MAX_Q': str(self.questions_per_bench),
            'PYTHONPATH': str(HERE) + os.pathsep + self.env.get('PYTHONPATH', ''),
            'SAMPLING_SEED': '0'})
        self.env['PATH'] = os.pathsep.join((str(self.py_original.parent), str(self.py_sglang.parent),
                                            self.env.get('PATH', '')))
        self.failures = []
        self.failed_this_run = set()
        self.environment = {}          # package-list hashes of every environment, part of each result's settings
        self.deepspeed_cuda_home = None    # stub CUDA dir for DeepSpeed when there is no CUDA toolkit (setup)
        self.active_server_log = None

    # ================================================================================================================
    # Bookkeeping: deadline, stage status, running commands
    # ================================================================================================================
    def remaining(self, cap=3600):
        """Seconds a stage may take: its own cap, but never past the night's deadline."""
        left = self.deadline - time.monotonic()
        if left <= 0:
            raise TimeoutError('Overall night deadline reached; completed results are preserved')
        return min(left, cap)

    def status(self, name, status, **extra):
        if status == 'FAILED':
            self.failed_this_run.add(name)
        self.stages[name] = {'status': status, 'at': time.time(), **extra}
        atomic_json(self.stages_path, self.stages)
        print(f'{time.strftime("%F %T")} {name}: {status}', flush=True)

    def attempt(self, name, fn, *args, **kwargs):
        """Run one stage; on failure record it and carry on. Only the deadline (TimeoutError) and signals stop."""
        try:
            return fn(*args, **kwargs)
        except TimeoutError:
            raise
        except Exception as exc:
            self.failures.append(name)
            if name not in self.failed_this_run:     # keep a more specific reason recorded by an inner stage
                self.status(name, 'FAILED', reason=f'{type(exc).__name__}: {exc}')
            print(f'{time.strftime("%F %T")} {name}: continuing with the next stage', flush=True)

    def command(self, name, cmd, cwd=HERE, timeout=3600, env=None):
        """Run a command as stage `name` (log: logs/<mode>/<name>.log)."""
        self.status(name, 'RUNNING')
        try:
            run_process(cmd, cwd=cwd, log=self.logs / (name + '.log'),
                        timeout=self.remaining(timeout), env=self.env if env is None else env)
        except BaseException as exc:
            self.status(name, 'FAILED', reason=f'{type(exc).__name__}: {exc}')
            raise
        self.status(name, 'SUCCEEDED')

    def produce(self, name, path, settings, validator, cmd, *, cwd=HERE, env=None, timeout=3600):
        """Make result `path` with `cmd`, unless it is already finished for the same settings."""
        manifest = {**self.base_manifest, 'stage': name, **settings}
        if finished(path, manifest, validator):
            self.status(name, 'REUSED')
            return
        if self.adopt_earlier_result(path, manifest, validator):
            self.status(name, 'ADOPTED')
            return
        if path.exists():       # an unfinished leftover is kept aside, never deleted
            os.replace(path, path.with_name(path.name + '.previous.' + str(time.time_ns())))
        try:
            self.command(name, cmd, cwd=cwd, env=env, timeout=timeout)
            server_log = self.active_server_log
            if server_log and 'Falling back to greedy verification' in server_log.read_text(
                    encoding='utf-8', errors='replace'):
                raise RuntimeError('T=1 degraded to greedy; result is not committed')
            validator(path)
            finish(path, manifest, validator)
        except BaseException as exc:
            self.status(name, 'FAILED', reason=f'{type(exc).__name__}: {exc}')
            raise

    # Settings that must be identical for an earlier result to be adopted (see adopt_earlier_result).
    ADOPT_KEYS = ('stage', 'protocol', 'temperature', 'tree', 'models', 'eagle', 'count', 'hardware')

    def adopt_earlier_result(self, path, manifest, validator):
        """Accept a 3a result finished by the previous code version (other marker format, SCHEMA 3).

        Only for the authors' benchmarks (their scripts are unchanged), and only if the result file is intact, is
        complete, and was made with the same settings, model revisions, hardware and the same installed packages
        of the eval environment. The result is then re-marked in the current format; nothing is recomputed.
        """
        if manifest.get('protocol') != 'unchanged-author' or not path.exists():
            return False
        try:
            earlier = read_json(done_path(path))
            old = json.loads(json.dumps(earlier['manifest']))
            new = json.loads(json.dumps(manifest))
            same = (earlier['sha256'] == file_hash(path)
                    and all(old.get(k) == new.get(k) for k in self.ADOPT_KEYS)
                    and old['environment']['eagle_env']['freeze_sha256']
                    == new['environment']['eagle_env']['freeze_sha256'])
            if not same:
                return False
            validator(path)
        except (OSError, ValueError, KeyError, TypeError):
            return False
        finish(path, manifest, validator)       # status ADOPTED in stages.json records where it came from
        return True

    # ================================================================================================================
    # Setup: pinned code, four environments, models
    # ================================================================================================================
    def checkout(self, folder, url, commit, name):
        """Clone `url` into `folder` (once) and check out `commit`; refuse if someone edited tracked files."""
        if not (folder / '.git').is_dir():
            if folder.exists():
                raise RuntimeError(f'{folder.name} exists without .git; refusing deletion')
            self.command(name + '_clone', ['git', 'clone', url, folder], timeout=900)
        git = ['git', '-C', str(folder)]
        current = subprocess.check_output(git + ['rev-parse', 'HEAD'], text=True).strip()
        edited = subprocess.check_output(git + ['status', '--porcelain', '--untracked-files=no'], text=True).strip()
        if edited:
            raise RuntimeError(f'{folder.name} has changes; refusing automatic checkout')
        if current != commit:
            self.command(name + '_fetch', ['git', '-C', folder, 'fetch', 'origin', commit], timeout=600)
            self.command(name + '_checkout', ['git', '-C', folder, 'checkout', '--detach', commit], timeout=60)
        if subprocess.check_output(git + ['rev-parse', 'HEAD'], text=True).strip() != commit:
            raise RuntimeError('Repository pin mismatch')

    def virtualenv(self, python, name, requirements, import_check):
        """Create/update a virtualenv; pip runs only when the requirement list changed. Then test the imports."""
        wanted = digest({'schema': SCHEMA, 'requirements': requirements, 'imports': import_check})
        marker = python.parent.parent / '.installed.json'
        if not python.exists():
            try:
                self.command(name + '_venv', [sys.executable, '-m', 'venv', python.parent.parent], timeout=120)
            except subprocess.CalledProcessError:
                # Some images (e.g. DataSphere) ship Python without ensurepip; `virtualenv` brings its own pip.
                shutil.rmtree(python.parent.parent, ignore_errors=True)
                self.command(name + '_virtualenv_install', [sys.executable, '-m', 'pip', 'install', '-q', 'virtualenv'],
                             timeout=600)
                self.command(name + '_virtualenv', [sys.executable, '-m', 'virtualenv', python.parent.parent],
                             timeout=300)
        try:
            up_to_date = read_json(marker)['desired'] == wanted
        except (OSError, ValueError, KeyError):
            up_to_date = False
        if not up_to_date:
            self.command(name + '_pip', [python, '-m', 'pip', 'install', *requirements], timeout=3600)
        self.command(name + '_imports', [python, '-c', import_check], timeout=120)
        freeze = subprocess.check_output([str(python), '-m', 'pip', 'freeze'], text=True, timeout=60)
        state = {'desired': wanted, 'freeze_sha256': digest(sorted(freeze.splitlines()))}
        atomic_json(marker, state)
        self.environment[name] = state

    def setup_inference_env(self):
        # The authors' eval scripts. fschat 0.2.31 imports openai/anthropic; versions of its time (pydantic 1).
        self.virtualenv(self.py_eagle, 'eagle_env',
            ['torch==2.5.1', 'transformers==4.53.2', 'fschat==0.2.31', 'openai==0.28.1', 'anthropic==0.3.11',
             'pydantic<2', 'accelerate', 'shortuuid', 'sentencepiece', 'protobuf', 'numpy', 'huggingface_hub',
             'requests', 'datasets', 'tqdm', 'matplotlib'],
            'import torch, transformers, fastchat.llm_judge.common; '
            'assert torch.__version__.split("+")[0]=="2.5.1"; assert transformers.__version__=="4.53.2"')

    def setup_training_envs(self):
        # The authors' trainer + DeepSpeed.
        self.virtualenv(self.py_original, 'original_env',
            ['torch==2.5.1', 'transformers==4.53.2', 'accelerate', 'datasets', 'safetensors', 'sentencepiece',
             'tqdm', 'numpy', 'protobuf', 'huggingface_hub', 'uv', 'wheel', 'setuptools', 'ninja'],
            'import torch, transformers, datasets; '
            'assert torch.__version__.split("+")[0]=="2.5.1"; assert transformers.__version__=="4.53.2"')
        # DeepSpeed 0.16.4 runs `$CUDA_HOME/bin/nvcc -V` at install AND at every import (op compatibility
        # checks). Without a CUDA toolkit it gets a stub nvcc that prints torch's CUDA version; nothing is compiled
        # (DS_BUILD_OPS=0, and the trainer uses torch's AdamW).
        deepspeed_env = dict(self.env, DS_BUILD_OPS='0')
        self.deepspeed_cuda_home = self.cuda_stub(self.py_original)
        if self.deepspeed_cuda_home:
            deepspeed_env['CUDA_HOME'] = self.deepspeed_cuda_home
        self.command('deepspeed_install', [self.py_original, '-m', 'pip', 'install', '--no-build-isolation',
                                           'deepspeed==0.16.4'], env=deepspeed_env, timeout=900)
        self.command('deepspeed_import', [self.py_original, '-c', 'import deepspeed; '
                                          'assert deepspeed.__version__.split("+")[0]=="0.16.4"'],
                     env=deepspeed_env, timeout=120)

        # NeMo AutoModel from source with its locked dependencies (uv). flash-attn needs a CUDA toolkit to build.
        self.checkout(TRAIN_DIR / 'Automodel', 'https://github.com/NVIDIA-NeMo/Automodel', NEMO_COMMIT, 'nemo')
        uv = self.py_original.parent / 'uv'
        automodel = TRAIN_DIR / 'Automodel'
        self.command('nemo_sync', [uv, 'sync', '--frozen'], cwd=automodel, timeout=3600)
        if shutil.which('nvcc') or os.environ.get('TRY_FA2', '0') == '1':
            try:
                self.command('nemo_fa2_install', [uv, 'sync', '--frozen', '--extra', 'fa'], cwd=automodel, timeout=900)
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
                self.command('nemo_restore_base', [uv, 'sync', '--frozen'], cwd=automodel, timeout=900)
        self.command('nemo_import', [self.py_nemo, '-c', 'import nemo_automodel.recipes.llm.train_eagle3'],
                     timeout=180)
        freeze = subprocess.check_output([str(uv), 'pip', 'freeze', '--python', str(self.py_nemo)],
                                         text=True, timeout=60)
        self.environment['nemo_env'] = {'commit': NEMO_COMMIT, 'freeze_sha256': digest(sorted(freeze.splitlines()))}

    def cuda_stub(self, python):
        """Without a CUDA toolkit: <venv>/stub_cuda/bin/nvcc that only prints the venv torch's CUDA version.

        Some packages only *ask* nvcc for the version or *store* CUDA_HOME at import (DeepSpeed's op checks,
        DeepGEMM's init) and compile nothing on our path. Returns the directory for CUDA_HOME, or None.
        """
        if shutil.which('nvcc'):
            return None
        version = subprocess.check_output([str(python), '-c', 'import torch; print(torch.version.cuda)'],
                                          text=True, timeout=60).strip()
        stub = python.parent.parent / 'stub_cuda/bin/nvcc'
        stub.parent.mkdir(parents=True, exist_ok=True)
        stub.write_text(f'#!/bin/sh\necho "Cuda compilation tools, release {version}, V{version}.0"\n',
                        encoding='utf-8')
        stub.chmod(0o755)
        return str(stub.parent.parent)

    def sglang_process_env(self):
        """Environment of SGLang processes: CUDA_HOME (and nvcc on PATH) for its start-up needs.

        SGLang 0.5.9 initialises DeepGEMM on import (it asserts CUDA_HOME exists) and JIT-compiles some kernels
        (e.g. RoPE) with nvcc at start-up, so it needs a real CUDA toolkit (setup_cuda.sh)."""
        # The draft's config says 2048 positions, the target's 131072; SGLang refuses the pair unless allowed.
        # Our requests stay under 1979 tokens, so the shorter draft context never matters.
        base = {**self.env, 'SGLANG_ALLOW_OVERWRITE_LONGER_CONTEXT_LEN': '1'}
        if not self.sglang_cuda_home:
            return base
        env = {**base, 'CUDA_HOME': self.sglang_cuda_home}
        bin_dir = Path(self.sglang_cuda_home) / 'bin'
        env['PATH'] = os.pathsep.join((str(bin_dir), env.get('PATH', '')))
        if (bin_dir / 'g++').exists():     # setup_cuda.sh's gcc 13: CUDA 12.8 refuses the newer system gcc
            env['NVCC_PREPEND_FLAGS'] = f'-ccbin {bin_dir / "g++"}'
        return env

    def sglang_cuda(self):
        """A real CUDA 12.8 toolkit for SGLang: the system one, else ../cuda-home made by setup_cuda.sh (once)."""
        if shutil.which('nvcc'):
            return None                       # a system toolkit: SGLang finds it by itself
        toolkit = HERE.parent / 'cuda-home'
        if not ((toolkit / 'bin/nvcc').exists() and (toolkit / 'bin/g++').exists()):
            self.attempt('cuda_toolkit', self.command, 'cuda_toolkit', ['bash', HERE / 'setup_cuda.sh'], timeout=3600)
        if (toolkit / 'bin/nvcc').exists():
            return str(toolkit)
        return self.cuda_stub(self.py_sglang)  # last resort: at least the import-time check passes

    def setup_sglang_env(self):
        self.virtualenv(self.py_sglang, 'sglang_env', ['sglang[all]==0.5.9', 'requests', 'datasets'],
                        'import sglang, requests, datasets; assert sglang.__version__.split("+")[0]=="0.5.9"')
        # A dependency pulls the newest `kernels` (needs huggingface_hub>=1.10, transformers 4.57 pins <1.0);
        # transformers imports it when present and every SGLang server dies at start. Without it: fine.
        self.command('sglang_drop_kernels', [self.py_sglang, '-m', 'pip', 'uninstall', '-y', 'kernels'], timeout=120)
        self.sglang_cuda_home = self.sglang_cuda()
        # Check the import chain the servers need (it pulls in DeepGEMM) once, here. If DeepGEMM still refuses,
        # remove its own package (never sgl-kernel): SGLang then gets an ImportError and runs without it.
        # A failure here only takes the SGLang stages down, not the night.
        self.attempt('sglang_import', self.import_sglang)

    def import_sglang(self):
        check = [self.py_sglang, '-c', 'import sglang.srt.speculative.spec_utils']
        try:
            self.command('sglang_import_check', check, env=self.sglang_process_env(), timeout=300)
            return
        except subprocess.CalledProcessError:
            pass
        owner = subprocess.check_output([str(self.py_sglang), '-c',
            'import importlib.metadata as m; print(" ".join(sorted({d.metadata["Name"] for d in m.distributions() '
            'if any(str(f).startswith("deep_gemm/") for f in (d.files or []))})))'], text=True, timeout=120).strip()
        if not owner or len(owner.split()) != 1 or 'gemm' not in owner.lower():
            raise RuntimeError(f'SGLang import fails and deep_gemm belongs to {owner!r}; not removing it')
        self.command('sglang_drop_deep_gemm', [self.py_sglang, '-m', 'pip', 'uninstall', '-y', owner], timeout=300)
        self.command('sglang_import_check', check, env=self.sglang_process_env(), timeout=300)

    def setup_models(self, inference):
        """Target (always) and draft (for inference) at their pinned revisions."""
        python = self.py_eagle if inference else self.py_original
        shared = TRAIN_DIR / 'models/llama31-8b-instruct'    # already downloaded by earlier training runs
        if not self.model.exists() and (shared / 'config.json').exists():
            self.model.parent.mkdir(parents=True, exist_ok=True)
            self.model.symlink_to(shared, target_is_directory=True)
        self.command('target_snapshot', [python, HERE / 'download.py', MODELS['target'][0], self.model,
                                         '*.json', '*.safetensors'], timeout=1800)
        if inference:
            self.command('draft_snapshot', [python, HERE / 'download.py', MODELS['draft'][0], self.draft,
                                            '*.json', '*.bin'], timeout=1200)

    def setup(self, inference=True, training=True, sglang=True):
        self.checkout(HERE / 'EAGLE', 'https://github.com/SafeAILab/EAGLE', EAGLE_COMMIT, 'eagle')
        if inference:
            self.setup_inference_env()
        if training:
            self.setup_training_envs()
        if sglang:
            self.setup_sglang_env()
        self.setup_models(inference or sglang)
        # Settings that every result depends on; a result is reused only if they are unchanged.
        self.base_manifest = {
            'schema': SCHEMA, 'mode': self.tag, 'models': MODELS, 'eagle': EAGLE_COMMIT, 'nemo': NEMO_COMMIT,
            'environment': self.environment, 'count': self.questions_per_bench,
            'target_snapshot': read_json(self.model / 'snapshot_manifest.json'),
            'hardware': subprocess.check_output(['nvidia-smi', '--query-gpu=name,driver_version,power.limit',
                                                 '--format=csv,noheader'], text=True, timeout=30).strip(),
            'threads': {k: self.env.get(k) for k in ('OMP_NUM_THREADS', 'MKL_NUM_THREADS')}}

    # ================================================================================================================
    # 3a. The authors' evaluation scripts
    # ================================================================================================================
    def author_benchmarks(self):
        """EAGLE-3 and plain generation with SafeAILab/EAGLE's own scripts, T=0 then T=1 (results/<mode>/eagle)."""
        wanted = os.environ.get('AUTHOR_TEMPERATURES', '0,1').split(',')
        for temperature, prefix in ((0, ''), (1, 't1_')):
            if str(temperature) not in wanted:
                continue
            for bench in BENCHES:
                expected = questions(HERE / 'EAGLE', bench, self.questions_per_bench)
                for use_eagle, script in ((True, 'gen_ea_answer_llama3chat'),
                                          (False, 'gen_baseline_answer_llama3chat')):
                    name = ('ea_' if use_eagle else 'base_') + prefix + bench
                    path = self.results / 'eagle' / (name + '.jsonl')
                    path.parent.mkdir(parents=True, exist_ok=True)
                    cmd = [self.py_eagle, '-m', 'eagle.evaluation.' + script, '--temperature', str(temperature),
                           '--ea-model-path', self.draft, '--base-model-path', self.model,
                           '--bench-name', bench, '--question-begin', '0',
                           '--question-end', str(self.questions_per_bench),
                           '--total-token', str(AUTHOR_TREE['total_token']), '--depth', str(AUTHOR_TREE['depth']),
                           '--top-k', str(AUTHOR_TREE['top_k']),
                           '--answer-file', path]
                    if use_eagle:
                        cmd += ['--use_eagle3']
                    settings = {'protocol': 'unchanged-author', 'temperature': temperature,
                                'tree': [AUTHOR_TREE['total_token'], AUTHOR_TREE['depth'], AUTHOR_TREE['top_k']]}
                    self.attempt(name, self.produce, name, path, settings,
                                 lambda p, e=expected: validate_answers(p, e, 'eagle'), cmd, cwd=HERE / 'EAGLE',
                                 timeout=int(os.environ.get('BENCH_TIMEOUT', '5400')))
                self.attempt('inference_summary', self.inference_summary)

    def inference_summary(self):
        self.command('inference_summary', [self.py_eagle, HERE / 'summarize.py', self.model, self.results],
                     timeout=120)

    # ================================================================================================================
    # 3b. SGLang
    # ================================================================================================================
    @contextlib.contextmanager
    def sglang_server(self, name, tree=None):
        """Start an SGLang server (plain, or EAGLE-3 with `tree` = (steps, topk, tokens)); yield its URL."""
        port = int(os.environ.get('SGLANG_PORT', '30000'))
        self.wait_for_free_port(port)
        if not all(shutil.which(x, path=self.env['PATH']) for x in ('gcc', 'g++', 'ninja')):
            raise RuntimeError('Missing gcc/g++/ninja for runtime kernels; run setup before the allocation')
        if tree:     # without the tree-sampling kernel SGLang silently verifies T=1 greedily
            self.command('tree_sampling_kernel', [self.py_sglang, '-c',
                'from sglang.srt.speculative.spec_utils import TREE_SPEC_KERNEL_AVAILABLE; '
                'assert TREE_SPEC_KERNEL_AVAILABLE, "T=1 would fall back to greedy"'],
                env=self.sglang_process_env(), timeout=300)
        # Triton attention and PyTorch sampling: kernels that need no CUDA toolkit (flashinfer may JIT-compile).
        cmd = [self.py_sglang, '-m', 'sglang.launch_server', '--model-path', self.model, '--dtype', 'float16',
               '--host', '127.0.0.1', '--port', str(port), '--mem-fraction-static', '0.8',
               '--attention-backend', 'triton', '--sampling-backend', 'pytorch', '--disable-radix-cache',
               '--random-seed', '0']     # tree verification at T=1 uses the server's global RNG
        if tree:
            steps, topk, tokens = tree
            cmd += ['--speculative-algorithm', 'EAGLE3', '--speculative-draft-model-path', self.draft,
                    '--speculative-num-steps', str(steps), '--speculative-eagle-topk', str(topk),
                    '--speculative-num-draft-tokens', str(tokens)]
        log = self.logs / ('server_' + name + '.log')
        url = f'http://127.0.0.1:{port}'
        proc = None
        with log.open('w', encoding='utf-8') as stream:
            try:
                proc = subprocess.Popen([str(x) for x in cmd], cwd=HERE, env=self.sglang_process_env(), stdout=stream,
                                        stderr=subprocess.STDOUT, start_new_session=True)
                self.wait_until_ready(proc, url, log, tree)
                self.active_server_log = log
                yield url
                if 'Falling back to greedy verification' in log.read_text(encoding='utf-8', errors='replace'):
                    raise RuntimeError('T=1 degraded to greedy verification')
            finally:
                self.active_server_log = None
                terminate_owned(proc)

    def wait_for_free_port(self, port, seconds=180):
        """The previous server may need a moment to release the port; we wait, but never kill its owner."""
        until = time.monotonic() + seconds
        while True:
            with socket.socket() as sock:
                sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)   # ignore TIME_WAIT leftovers
                try:
                    sock.bind(('127.0.0.1', port))
                    return
                except OSError:
                    if time.monotonic() > until:
                        raise RuntimeError(f'Port {port} is still taken after {seconds} s')
            time.sleep(2)

    def wait_until_ready(self, proc, url, log, tree):
        """Poll /server_info until the server answers, and check it runs the model and tree we asked for."""
        name = log.stem.removeprefix('server_')
        until = time.monotonic() + self.remaining(600)
        while time.monotonic() < until:
            if proc.poll() is not None:
                raise RuntimeError(f'Server exited ({proc.returncode}): {log.name}')
            try:
                info = http_json(url + '/server_info')
            except (OSError, json.JSONDecodeError):
                time.sleep(1)
                continue
            server_args = info.get('server_args', info)
            if Path(server_args['model_path']).resolve() != self.model.resolve():
                raise RuntimeError('Wrong server target model')
            if tree:
                keys = ('speculative_num_steps', 'speculative_eagle_topk', 'speculative_num_draft_tokens')
                if any(server_args.get(k) != v for k, v in zip(keys, tree)):
                    raise RuntimeError('Wrong speculative server configuration')
            elif server_args.get('speculative_algorithm') not in (None, 'NONE'):
                raise RuntimeError('Expected a plain server')
            atomic_json(self.logs / ('server_' + name + '.json'), info)
            return
        # Not TimeoutError: that one means "the night is over" and would stop every remaining stage.
        raise RuntimeError('Server did not start in time')

    def sglang_benchmarks(self):
        """For each server config: start the server once, run every unfinished benchmark against it."""
        configs = [('base', None)] + [(name, (steps, topk, tokens)) for name, steps, topk, tokens in SGLANG_TREES]
        for name, tree in configs:
            temperatures = (0, 1) if name in SGLANG_T1_CONFIGS else (0,)
            jobs = []
            for temperature in temperatures:
                seeds = (0, 1, 2) if temperature and not self.smoke else (0,)
                for seed in seeds:
                    prefix = name + ('_t1' if temperature else '') + (f'_seed{seed}' if seed else '')
                    for bench in BENCHES:
                        path = self.results / 'sglang' / f'{prefix}_{bench}.json'
                        expected = questions(HERE / 'EAGLE', bench, self.questions_per_bench)
                        settings = {'protocol': 'bounded-http-no-prefix-cache-v2', 'tree': tree,
                                    'temperature': temperature, 'seed': seed}
                        manifest = {**self.base_manifest, 'stage': prefix + '_' + bench, **settings}
                        validator = lambda p, e=expected: validate_answers(p, e, 'sglang')
                        if finished(path, manifest, validator):
                            self.status(prefix + '_' + bench, 'REUSED')
                        else:
                            jobs.append((prefix, bench, temperature, seed, path, settings, validator))
            if jobs:
                self.attempt('server_' + name, self.run_sglang_jobs, name, tree, jobs)

    def run_sglang_jobs(self, name, tree, jobs):
        with self.sglang_server(name, tree) as url:
            for prefix, bench, temperature, seed, path, settings, validator in jobs:
                env = {**self.env, 'SPECULATIVE': '1' if tree else '0', 'SAMPLING_SEED': str(seed)}
                stage = prefix + '_' + bench
                self.attempt(stage, self.produce, stage, path, settings, validator,
                             [self.py_sglang, HERE / 'sglang_client.py', url, self.model, bench, path,
                              str(temperature)],
                             env=env, timeout=int(os.environ.get('BENCH_TIMEOUT', '5400')))
                self.attempt('inference_summary', self.inference_summary)

    # ================================================================================================================
    # 4. Training step speed
    # ================================================================================================================
    def training_data(self):
        """One tokenized corpus + 32K vocabulary for both trainers (../nemo_speed/prepare_data.py)."""
        data = self.train_out / 'data'

        def validate(path):
            stats = read_json(path)
            if stats['samples'] != self.train_examples or stats['canonical_sha256'] != file_hash(
                    data / 'canonical.jsonl'):
                raise ValueError('Wrong training data')
            if stats['mapping_sha256'] != digest(read_json(data / 'selected_tokens.json')):
                raise ValueError('Wrong mapping')

        settings = {'N': self.train_examples, 'revision': TRAIN_DATA_REVISION, 'protocol': 'shared-author-tokens'}
        self.produce('training_data', data / 'stats.json', settings, validate,
                     [self.py_original, TRAIN_DIR / 'prepare_data.py', self.model, str(self.train_examples), data,
                      HERE / 'EAGLE'], timeout=1800)
        return data

    def training_speed(self, variants=False):
        """variants=False: the authors' trainer and plain NeMo. variants=True: NeMo's speed-ups."""
        data = self.training_data()
        common_settings = {'data': file_hash(data / 'canonical.jsonl'),
                           'mapping': file_hash(data / 'selected_tokens.json'),
                           'N': self.train_examples, 'warmup': self.warmup_steps,
                           'protocol': 'matched-bf16-fixed2048-v1'}
        if not variants:
            self.original_trainer(data, common_settings, 'matched')
            self.original_trainer(data, common_settings, 'asis')
        runs = [('nemo_eager_nopack', 'eager', 0, None)] if not variants else [
            ('nemo_eager_pack', 'eager', 2048, None),
            ('nemo_fa2_pack', 'flash_attention_2', 2048, None),
            ('nemo_compile', 'eager', 2048, 'compile'),
            ('nemo_compile_fp8', 'eager', 2048, 'fp8'),
            ('nemo_fa2_pack_mb4', 'flash_attention_2', 2048, 'mb4')]
        has_fa2 = subprocess.run([str(self.py_nemo), '-c', 'import flash_attn'], env=self.env,
                                 stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=60).returncode == 0
        for name, attention, packing, extra in runs:
            self.nemo_trainer(data, common_settings, name, attention, packing, extra, has_fa2)

    def original_trainer(self, data, common_settings, mode):
        """The authors' traineagle3/main.py, prepared by ../nemo_speed/patch_original.py.

        mode='matched': the same work as the NeMo runs (bf16, rows padded to 2048, no checkpointing).
        mode='asis':    the authors' own settings (fp16, checkpointing, no padding, their lr schedule).
        """
        name = 'original' if mode == 'matched' else 'original_asis'
        work = self.train_out / 'work' / name
        out = self.train_out / (name + '.speed.json')
        settings = {**common_settings, 'backend': 'original', 'batch': [1, 2], 'packing': 0, 'mode': mode}
        if mode == 'asis':
            settings['protocol'] = 'author-as-is-fp16-v1'
        if not finished(out, {**self.base_manifest, 'stage': 'train_' + name, **settings}, validate_speed):
            self.attempt('patch_' + name, self.command, 'patch_' + name,
                         [self.py_original, TRAIN_DIR / 'patch_original.py', HERE / 'EAGLE', str(self.warmup_steps),
                          work, mode], timeout=60)
        env = {**self.env, 'SHARED_MAPPING': str(data / 'selected_tokens.json'), 'SPEED_OUTPUT': str(out)}
        if self.deepspeed_cuda_home:
            env['CUDA_HOME'] = self.deepspeed_cuda_home
        self.attempt('train_' + name, self.produce, 'train_' + name, out, settings, validate_speed,
                     [self.py_original, '-m', 'deepspeed.launcher.runner', '--num_gpus', '1', 'main.py',
                      '--deepspeed_config', 'ds_config.json', '--basepath', self.model,
                      '--trainpath', data / 'canonical.jsonl', '--testpath', data / 'test_canonical.jsonl',
                      '--savedir', work / 'out'], cwd=work, env=env, timeout=1800)

    def nemo_trainer(self, data, common_settings, name, attention, packing, extra, has_fa2):
        """One NeMo run: nemo_config.yaml filled in, plus compile / FP8 / micro-batch 4 if asked."""
        if attention == 'flash_attention_2' and not has_fa2:
            self.status('train_' + name, 'UNSUPPORTED', reason='flash-attn 2 is absent; no eager result under FA2 label')
            return
        if extra in ('compile', 'fp8') and not all(shutil.which(x, path=self.env['PATH']) for x in ('gcc', 'g++')):
            self.status('train_' + name, 'UNSUPPORTED', reason='Missing C/C++ compiler')
            return
        config = (HERE / 'nemo_config.yaml').read_text(encoding='utf-8')
        for key, value in {'__MODEL__': self.model, '__DATA__': data / 'canonical.jsonl',
                           '__OUT__': self.train_out / 'work' / name, '__ATTN__': attention,
                           '__PACK__': packing}.items():
            # paths as JSON strings: valid YAML even with spaces
            config = config.replace(key, json.dumps(str(value)) if isinstance(value, Path) else str(value))
        if extra in ('compile', 'fp8'):
            config += '\ncompile:\n  enabled: true\n  mode: default\n'
        if extra == 'fp8':
            config += '\nfp8:\n  enabled: true\n  recipe_name: tensorwise\n  filter_fqns: ["lm_head"]\n  emulate: false\n'
        if extra == 'mb4':
            config = (config.replace('micro_batch_size: 1', 'micro_batch_size: 4')
                            .replace('grad_accumulation_steps: 2', 'grad_accumulation_steps: 1'))
        config_path = self.train_out / 'work' / (name + '.yaml')
        atomic_text(config_path, config)
        out = self.train_out / (name + '.speed.json')
        settings = {**common_settings, 'backend': 'nemo', 'configuration_sha256': digest(config),
                    'attention': attention}
        self.attempt('train_' + name, self.produce, 'train_' + name, out, settings, validate_speed,
                     [self.py_nemo, HERE / 'train_nemo.py', '--config', config_path,
                      '--data', data / 'canonical.jsonl', '--mapping', data / 'selected_tokens.json',
                      '--out', out, '--warmup', str(self.warmup_steps)],
                     cwd=TRAIN_DIR / 'Automodel', timeout=1800)
        self.attempt('training_summary', self.training_summary)

    def training_summary(self):
        self.command('training_summary', [self.py_original, HERE / 'stamp_and_summarize.py', 'summary',
                                          self.train_out], timeout=60)

    # ================================================================================================================
    # 5. Regeneration probe and budget
    # ================================================================================================================
    def regeneration_probe(self):
        from regen_probe import validate_probe
        path = self.results / 'regen_probe.json'
        settings = {'protocol': 'stratified-multiturn-fixed1900-v2',
                    'samples_per_bucket': 2 if self.smoke else 64,
                    'scan_limit': 64 if self.smoke else 8192,
                    'concurrency': 8 if self.smoke else 64}
        if finished(path, {**self.base_manifest, 'stage': 'regeneration', **settings}, validate_probe):
            self.status('regeneration', 'REUSED')
            return
        with self.sglang_server('regeneration') as url:
            self.produce('regeneration', path, settings, validate_probe,
                         [self.py_sglang, HERE / 'regen_probe.py', url, self.model, path,
                          '--samples-per-bucket', str(settings['samples_per_bucket']),
                          '--scan-limit', str(settings['scan_limit']),
                          '--concurrency', str(settings['concurrency'])], timeout=1800)

    def budget(self):
        if (self.results / 'regen_probe.json').exists() and (self.train_out / 'summary.json').exists():
            python = self.py_original if self.py_original.exists() else self.py_eagle
            self.command('budget', [python, HERE / 'budget.py', '--probe', self.results / 'regen_probe.json',
                                    '--training', self.train_out / 'summary.json',
                                    '--out', self.results / 'budget.md'], timeout=60)
        else:
            self.status('budget', 'BLOCKED', reason='Validated regeneration/training results required')

    # ================================================================================================================
    # The night
    # ================================================================================================================
    def profile(self):
        """Where the time of an EAGLE round goes on this GPU (profile_eagle.py), and its pictures."""
        out = self.results / 'profile'
        self.command('profile', [self.py_eagle, HERE / 'profile_eagle.py', '--model', self.model, '--draft', self.draft,
                                 '--out', out], cwd=HERE / 'EAGLE', timeout=3600)
        self.command('profile_plots', [self.py_eagle, HERE / 'plot_profile.py', out], timeout=1800)

    def run(self):
        if self.mode == 'author':     # the authors' code only, e.g. on another GPU: profile first (fast), then 3a
            self.setup(inference=True, training=False, sglang=False)
            self.attempt('profile', self.profile)
            self.attempt('author_benches', self.author_benchmarks)
            if self.failures:
                raise RuntimeError('Failed stages (the rest ran): ' + ', '.join(dict.fromkeys(self.failures)))
            return
        inference = self.mode in ('night', 'inference', 'check')
        training = self.mode in ('night', 'train', 'check')
        self.setup(inference=self.mode != 'train', training=self.mode in ('night', 'train', 'check', 'setup'),
                   sglang=self.mode != 'train')
        if os.environ.get('ENV_ONLY', '0') == '1' or self.mode == 'setup':
            return
        if inference:
            self.attempt('author_benches', self.author_benchmarks)                   # 3a
        if training:
            self.attempt('training', self.training_speed)                            # 4, baseline
            self.attempt('training_summary', self.training_summary)
        if inference:
            self.attempt('regeneration', self.regeneration_probe)                    # 5
            self.attempt('budget', self.budget)
            self.attempt('sglang_benches', self.sglang_benchmarks)                   # 3b
        if training:
            self.attempt('training_variants', self.training_speed, variants=True)    # 4, NeMo speed-ups
            self.attempt('training_summary', self.training_summary)
        self.attempt('budget', self.budget)
        if self.failures:
            raise RuntimeError('Failed stages (the rest ran): ' + ', '.join(dict.fromkeys(self.failures)))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('mode', choices=('night', 'inference', 'train', 'check', 'setup', 'author'))
    args = parser.parse_args()
    if os.name != 'posix':
        raise SystemExit('GPU orchestration requires Linux; run tests locally on Windows')
    import fcntl
    import signal
    with (HERE / '.night.lock').open('a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)      # one run of this package at a time

        def on_sigterm(signum, frame):
            raise KeyboardInterrupt(f'Received signal {signum}; cleaning owned processes')
        signal.signal(signal.SIGTERM, on_sigterm)

        night = Night(args.mode)
        try:
            night.run()
            night.status('overall', 'SUCCEEDED')
        except BaseException as exc:
            night.status('overall', 'FAILED', reason=f'{type(exc).__name__}: {exc}')
            print(f'FAILED: {exc}; see {night.stages_path}', file=sys.stderr)
            raise


if __name__ == '__main__':
    main()
